#!/usr/bin/env python3
"""Generate offline IPA for every phrase recognized by the learning data.

Build-only dependencies (the web app has no Python dependency):
    python -m pip install phonemizer espeakng-loader
"""
from __future__ import annotations

import json
from pathlib import Path

import espeakng_loader
from phonemizer.backend import EspeakBackend
from phonemizer.backend.espeak.wrapper import EspeakWrapper


ROOT = Path(__file__).resolve().parent
IPA_OVERRIDES = {
    # eSpeak NG reads isolated enclitic -y as the letter name “i grec”.
    "allez-y": "alˈezi",
}


def normalize(text: str) -> str:
    return text.lower().replace("’", "'").strip()


def load_learning_data() -> dict:
    source = (ROOT / "learning-data-4000.js").read_text(encoding="utf-8")
    prefix = "window.LEARNING_DATA="
    if not source.startswith("/*") or prefix not in source:
        raise RuntimeError("learning-data-4000.js has an unexpected format")
    payload = source[source.index(prefix) + len(prefix):].strip().removesuffix(";")
    return json.loads(payload)


def build() -> None:
    learning = load_learning_data()
    phrases = {
        normalize(phrase["text"])
        for annotation in learning["sentences"].values()
        for phrase in annotation.get("phrases", [])
    }
    EspeakWrapper.set_library(espeakng_loader.get_library_path())
    EspeakWrapper.set_data_path(espeakng_loader.get_data_path())
    backend = EspeakBackend("fr-fr", with_stress=True)
    ordered = sorted(phrases)
    phonemes = backend.phonemize(ordered, strip=True)
    entries = {
        text: {"ipa": IPA_OVERRIDES.get(text, ipa.strip().replace("-", ""))}
        for text, ipa in zip(ordered, phonemes)
    }
    data = {
        "version": "2026-09-22.1",
        "locale": "fr-FR",
        "source": "eSpeak NG",
        "phrases": entries,
    }
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    (ROOT / "pronunciation-data-4000.js").write_text(
        "/* Generated by build_pronunciation_data.py; do not edit by hand. */\n"
        "window.PRONUNCIATION_DATA=" + payload + ";\n",
        encoding="utf-8",
    )
    print(f"wrote IPA for {len(entries)} recognized phrases")


if __name__ == "__main__":
    build()
