#!/usr/bin/env python3
"""Build reference sentence IPA for the background introductions (eSpeak NG)."""
import json
import re
from pathlib import Path

import espeakng_loader
from phonemizer.backend import EspeakBackend
from phonemizer.backend.espeak.wrapper import EspeakWrapper

ROOT = Path(__file__).resolve().parent
SOURCE = (ROOT / 'france-scenes.js').read_text(encoding='utf-8')
ADDITIONAL = ''.join((ROOT / name).read_text(encoding='utf-8') for name in (
    'france-scenes-more.js', 'france-scenes-deeper.js', 'france-history.js', 'france-people.js'))
ORIGINAL = re.compile(r"\{fr:([\"'])(.*?)\1,zh:")
ADDED = re.compile(r"^\s+\[([\"'])(.*?)\1,", re.MULTILINE)
sentences = [match[1] for match in ORIGINAL.findall(SOURCE) + ADDED.findall(SOURCE + ADDITIONAL)]
if len(sentences) != 477 or len(set(sentences)) != 477:
    raise SystemExit(f'Expected 477 distinct introduction sentences, got {len(sentences)} ({len(set(sentences))} unique)')
EspeakWrapper.set_library(espeakng_loader.get_library_path())
EspeakWrapper.set_data_path(espeakng_loader.get_data_path())
backend = EspeakBackend('fr-fr', with_stress=False)
ipa = backend.phonemize(sentences, strip=True)
payload = dict(zip(sentences, (item.strip().replace('-', '') for item in ipa)))
(ROOT / 'france-scenes-ipa.js').write_text(
    '/* Generated by build_scene_ipa.py; eSpeak NG reference IPA, not a phonetic alignment. */\n'
    'window.FRANCE_SCENE_IPA=' + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ';\n',
    encoding='utf-8',
)
print(f'Wrote IPA for {len(payload)} introduction sentences')
