// Curated teaching data. The JSON payload is also read by build_phonetics_audio.py.
window.PHONETICS_DATA = {
  "version": "phonetics-v1",
  "groups": {"oral":"口元音", "nasal":"鼻元音", "consonant":"辅音", "glide":"半元音"},
  "letters": [
    {"id":"a","symbol":"A","name":"a","ipa":"a","tip":"张口发单元音，不要读成英语的 /eɪ/。字母名不等于它在每个单词里的读音。","example":"ami"},
    {"id":"b","symbol":"B","name":"bé","ipa":"be","tip":"先双唇闭合发 /b/，再接 /e/；末尾不要滑向 /i/。","example":"beau"},
    {"id":"c","symbol":"C","name":"cé","ipa":"se","tip":"字母名读 /se/。词中 c 在 e、i、y 前常读 /s/，其他位置常读 /k/；ç 读 /s/。","example":"sac"},
    {"id":"d","symbol":"D","name":"dé","ipa":"de","tip":"舌尖抵上齿附近，接稳定的 /e/，不要读成英语的 dee。","example":"dos"},
    {"id":"e","symbol":"E","name":"e","ipa":"ə","tip":"轻圆唇。字母名也常实现为接近 [ø] 的音；词中的 e、é、è 读音不能混为一谈。","example":"le"},
    {"id":"f","symbol":"F","name":"effe","ipa":"ɛf","tip":"先较开口的 /ɛ/，再让上齿轻触下唇发 /f/；结尾不补元音。","example":"fou"},
    {"id":"g","symbol":"G","name":"gé","ipa":"ʒe","tip":"先发有声的 /ʒ/，接 /e/。与 J /ʒi/ 的区别在后面的元音。","example":"gare"},
    {"id":"h","symbol":"H","name":"ache","ipa":"aʃ","tip":"字母名读 /aʃ/。常规法语词里的 h 不发 /h/；h aspiré 主要影响连音与省音。","example":"huit"},
    {"id":"i","symbol":"I","name":"i","ipa":"i","tip":"舌位高而靠前，嘴唇不收圆；不要读成英语的 /aɪ/。","example":"si"},
    {"id":"j","symbol":"J","name":"ji","ipa":"ʒi","tip":"/ʒ/ 后接 /i/，不要与 G /ʒe/ 互换，也不要读成英语的 jay。","example":"jour"},
    {"id":"k","symbol":"K","name":"ka","ipa":"ka","tip":"/k/ 后直接接 /a/，不是英语的 /keɪ/。词中的 k 也通常读 /k/，如 parking。","example":"parking"},
    {"id":"l","symbol":"L","name":"elle","ipa":"ɛl","tip":"/ɛ/ 后舌尖轻抵上齿龈，气流从舌两侧通过；末尾不补音。","example":"lit"},
    {"id":"m","symbol":"M","name":"emme","ipa":"ɛm","tip":"/ɛ/ 后双唇闭合，气流经过鼻腔；不要读成两个音节。","example":"mot"},
    {"id":"n","symbol":"N","name":"enne","ipa":"ɛn","tip":"/ɛ/ 后舌尖抵上齿龈，发清楚的 /n/；字母名不是鼻元音 /ɛ̃/。","example":"nous"},
    {"id":"o","symbol":"O","name":"o","ipa":"o","tip":"圆唇，保持一个稳定的元音，不要像英语一样滑动。","example":"mot"},
    {"id":"p","symbol":"P","name":"pé","ipa":"pe","tip":"双唇闭合后放开，再接 /e/；不要读成英语的 pee。","example":"pas"},
    {"id":"q","symbol":"Q","name":"Q","ipa":"ky","tip":"字母名是 /k/ 后接圆唇的 /y/，不是 /ku/，也不是英语的 /kjuː/。词中的 qu 通常整体读 /k/，如 qui /ki/。","example":"qui"},
    {"id":"r","symbol":"R","name":"erre","ipa":"ɛʁ","tip":"/ɛ/ 后接口腔后部的法语 r。不要卷舌，也不用刻意猛烈清嗓。","example":"rue"},
    {"id":"s","symbol":"S","name":"esse","ipa":"ɛs","tip":"/ɛ/ 后接清辅音 /s/；词中单个 s 夹在元音之间常读 /z/。","example":"sac"},
    {"id":"t","symbol":"T","name":"té","ipa":"te","tip":"舌尖抵上齿附近后放开，接 /e/；送气比普通话的 t 轻。","example":"tout"},
    {"id":"u","symbol":"U","name":"u","ipa":"y","tip":"舌位保持 /i/，同时把嘴唇收圆。U /y/ 与 ou /u/ 是不同的音。","example":"tu"},
    {"id":"v","symbol":"V","name":"vé","ipa":"ve","tip":"上齿轻触下唇并让声带振动，接 /e/。与 B /be/ 的唇齿动作不同。","example":"vous"},
    {"id":"w","symbol":"W","name":"double vé","ipa":"dublə ve","tip":"法国法语的字母名是 double vé，不是英语的 double u；连贯说时中间的 /ə/ 可弱化。词中可读 /v/ 或 /w/，如法国法语的 wagon 通常读 /vaɡɔ̃/。","example":"wagon"},
    {"id":"x","symbol":"X","name":"ixe","ipa":"iks","tip":"依次发 /i/、/k/、/s/，合成一个音节；结尾不补元音。","example":"six"},
    {"id":"y","symbol":"Y","name":"i grec","ipa":"i ɡʁɛk","tip":"字母名是 i grec，意为“希腊 i”；它在词中常对应 /i/ 或 /j/。","example":"yeux"},
    {"id":"z","symbol":"Z","name":"zède","ipa":"zɛd","tip":"先发有声的 /z/，再接 /ɛd/；末尾 /d/ 要保留。","example":"zéro"}
  ],
  "sounds": [
    {"id":"i","symbol":"i","group":"oral","name":"闭前不圆唇元音","tip":"舌位高而靠前，嘴唇自然展开；整个音保持稳定。","spelling":"i、î、y","example":"si","file":"Close front unrounded vowel.ogg"},
    {"id":"y","symbol":"y","group":"oral","name":"闭前圆唇元音","tip":"先摆出 /i/ 的舌位，再收圆嘴唇；舌头不要跟着向后移。","spelling":"u、û","example":"tu","file":"Close front rounded vowel.ogg"},
    {"id":"u","symbol":"u","group":"oral","name":"闭后圆唇元音","tip":"嘴唇收圆，舌位高而靠后；注意和前舌的 /y/ 区分。","spelling":"ou、où、oû","example":"nous","file":"Close back rounded vowel.ogg"},
    {"id":"e","symbol":"e","group":"oral","name":"半闭前不圆唇元音","tip":"开口较小，舌位靠前；保持单元音，不要加 /i/ 的滑动。","spelling":"é、-er、-ez（常见情况）","example":"été","file":"Close-mid front unrounded vowel.ogg"},
    {"id":"eu-close","symbol":"ø","group":"oral","name":"半闭前圆唇元音","tip":"舌位接近 /e/，嘴唇收圆；比 /œ/ 的开口小。","spelling":"eu、œu（如 peu、vœu）","example":"peu","file":"Close-mid front rounded vowel.ogg"},
    {"id":"o-close","symbol":"o","group":"oral","name":"半闭后圆唇元音","tip":"圆唇，开口较小；不带英语式的尾部滑音。","spelling":"eau、au、ô、部分 o","example":"eau","file":"Close-mid back rounded vowel.ogg"},
    {"id":"schwa","symbol":"ə","group":"oral","name":"弱读 e（央元音）","tip":"轻松、短促地发音。法语里常接近 [œ] 或 [ø]；语流中有时省略，不是任何位置都能删掉。","spelling":"部分不带重音符号的 e","example":"le","file":"Mid-central vowel.ogg"},
    {"id":"e-open","symbol":"ɛ","group":"oral","name":"半开前不圆唇元音","tip":"舌位靠前，开口比 /e/ 大；注意 é /e/ 与 è /ɛ/ 的区别。","spelling":"è、ê、ai、ei（常见情况）","example":"mère","file":"Open-mid front unrounded vowel.ogg"},
    {"id":"eu-open","symbol":"œ","group":"oral","name":"半开前圆唇元音","tip":"舌位接近 /ɛ/，嘴唇收圆；比 /ø/ 更开。","spelling":"eu、œu（如 fleur、cœur）","example":"fleur","file":"Open-mid front rounded vowel.ogg"},
    {"id":"o-open","symbol":"ɔ","group":"oral","name":"半开后圆唇元音","tip":"舌位靠后、嘴唇圆，开口比 /o/ 更大。","spelling":"部分 o（如 porte）","example":"porte","file":"Open-mid back rounded vowel.ogg"},
    {"id":"a","symbol":"a","group":"oral","name":"开前不圆唇元音","tip":"嘴巴自然张开，嘴唇不收圆；法语实际舌位可比参考音更居中。","spelling":"a、à","example":"ami","file":"Open front unrounded vowel.ogg"},
    {"id":"a-back","symbol":"ɑ","group":"oral","name":"开后不圆唇元音","tip":"开口大，舌位比 /a/ 靠后。现代法国法语中不少人已把 /ɑ/ 与 /a/ 合并。","spelling":"â、部分 a（传统区分）","example":"pâte","file":"Open back unrounded vowel.ogg","variant":true},
    {"id":"in","symbol":"ɛ̃","group":"nasal","name":"前部不圆唇鼻元音","tip":"开口、舌位靠前，让气流同时经过口鼻；不要在末尾另补 /n/ 或 /ŋ/。","spelling":"in、im、ain、ein（鼻化环境）","example":"pain","file":"Nasalised open-mid front unrounded vowel.ogg"},
    {"id":"un","symbol":"œ̃","group":"nasal","name":"前部圆唇鼻元音","tip":"圆唇鼻化；不少法国说话者会与 /ɛ̃/ 合并。这里保留传统区别，参考音用比利时法语 un（仅此一个元音）示范。","spelling":"un、um（鼻化环境）","example":"un","file":"Fr-un-fr BE.ogg","variant":true},
    {"id":"an","symbol":"ɑ̃","group":"nasal","name":"后部不圆唇鼻元音","tip":"张口，舌位偏后，气流经过口鼻；不要读成 /a/ 加 /n/。","spelling":"an、am、en、em（鼻化环境）","example":"sans","file":"Nasalised open back unrounded vowel.ogg"},
    {"id":"on","symbol":"ɔ̃","group":"nasal","name":"后部圆唇鼻元音","tip":"圆唇鼻化，不补 n 音。现代法国法语的实际音常比参考音更闭，接近 [õ]。","spelling":"on、om（鼻化环境）","example":"bon","file":"Nasalised open-mid back rounded vowel.ogg"},
    {"id":"p","symbol":"p","group":"consonant","name":"清双唇塞音","tip":"双唇闭合后短促放开，声带不振动；不需要强送气。","spelling":"p、pp","example":"pas","file":"Voiceless bilabial plosive.ogg"},
    {"id":"b","symbol":"b","group":"consonant","name":"浊双唇塞音","tip":"双唇闭合后放开，让声带振动；不是把 /p/ 用力读。","spelling":"b、bb","example":"beau","file":"Voiced bilabial plosive.ogg"},
    {"id":"t","symbol":"t","group":"consonant","name":"清齿／齿龈塞音","tip":"舌尖抵上齿附近后放开，声带不振动；法语位置通常比通用 IPA 参考音更靠前。","spelling":"t、tt","example":"tout","file":"Voiceless alveolar plosive.ogg"},
    {"id":"d","symbol":"d","group":"consonant","name":"浊齿／齿龈塞音","tip":"舌尖抵上齿附近后放开，同时让声带振动。","spelling":"d、dd","example":"dos","file":"Voiced alveolar plosive.ogg"},
    {"id":"k","symbol":"k","group":"consonant","name":"清软腭塞音","tip":"舌后部接触软腭后放开，声带不振动，送气较轻。","spelling":"c、qu、k（依词而定）","example":"car","file":"Voiceless velar plosive.ogg"},
    {"id":"g","symbol":"ɡ","group":"consonant","name":"浊软腭塞音","tip":"舌后部接触软腭后放开，声带振动；不要与 /ʒ/ 混淆。","spelling":"g、gu（如 gare、guide）","example":"gare","file":"Voiced velar plosive.ogg"},
    {"id":"f","symbol":"f","group":"consonant","name":"清唇齿擦音","tip":"上齿轻触下唇，让气流摩擦通过，声带不振动。","spelling":"f、ff、ph","example":"fou","file":"Voiceless labiodental fricative.ogg"},
    {"id":"v","symbol":"v","group":"consonant","name":"浊唇齿擦音","tip":"嘴形与 /f/ 相似，但声带振动；不要用双唇闭合的 /b/ 代替。","spelling":"v","example":"vous","file":"Voiced labiodental fricative.ogg"},
    {"id":"s","symbol":"s","group":"consonant","name":"清齿龈擦音","tip":"舌尖靠近上齿龈，让气流从窄缝通过，声带不振动。","spelling":"s、ss、ç、部分 c","example":"sac","file":"Voiceless alveolar sibilant.ogg"},
    {"id":"z","symbol":"z","group":"consonant","name":"浊齿龈擦音","tip":"嘴形接近 /s/，同时让声带振动；元音之间的单个 s 常读这个音。","spelling":"z、元音之间的 s","example":"zéro","file":"Voiced alveolar sibilant.ogg"},
    {"id":"sh","symbol":"ʃ","group":"consonant","name":"清后齿龈擦音","tip":"舌位比 /s/ 稍后，双唇可略圆；不卷舌，声带不振动。","spelling":"ch（常见情况）","example":"chat","file":"Voiceless palato-alveolar sibilant.ogg"},
    {"id":"zh","symbol":"ʒ","group":"consonant","name":"浊后齿龈擦音","tip":"嘴形接近 /ʃ/，让声带振动；不要在前面加 /d/。","spelling":"j、g 在 e/i/y 前","example":"jour","file":"Voiced palato-alveolar sibilant.ogg"},
    {"id":"m","symbol":"m","group":"consonant","name":"双唇鼻音","tip":"闭合双唇，声带振动，气流从鼻腔通过。","spelling":"m、mm","example":"mot","file":"Bilabial nasal.ogg"},
    {"id":"n","symbol":"n","group":"consonant","name":"齿龈鼻音","tip":"舌尖抵上齿龈，气流经过鼻腔；它是辅音，不是鼻化元音。","spelling":"n、nn","example":"nous","file":"Alveolar nasal.ogg"},
    {"id":"gn","symbol":"ɲ","group":"consonant","name":"硬腭鼻音","tip":"舌面前部贴近硬腭，气流经鼻腔；连成一个音，不要拆出一个额外音节。","spelling":"gn（常见情况）","example":"montagne","file":"Palatal nasal.ogg"},
    {"id":"ng","symbol":"ŋ","group":"consonant","name":"软腭鼻音（借词）","tip":"舌后部抵软腭，气流经鼻腔；常出现在 -ing 借词，不要再补 /ɡ/。","spelling":"-ing 借词","example":"parking","file":"Velar nasal.ogg","variant":true},
    {"id":"l","symbol":"l","group":"consonant","name":"齿龈边音","tip":"舌尖抵上齿龈，让气流从舌两边通过；不必把舌后部抬得很高。","spelling":"l、ll（并非所有 ill）","example":"lit","file":"Alveolar lateral approximant.ogg"},
    {"id":"r","symbol":"ʁ","group":"consonant","name":"浊小舌擦音（法语 r）","tip":"摩擦在口腔后部，不卷舌、不用力清嗓；实际语流里可弱化，也可能清化。","spelling":"r、rr","example":"rue","file":"Voiced uvular fricative.ogg"},
    {"id":"j","symbol":"j","group":"glide","name":"硬腭近音","tip":"从接近 /i/ 的舌位迅速滑向后面的元音，不另占一个完整音节；不是字母 J 的名称。","spelling":"y、部分 i、ill","example":"yeux","file":"Palatal approximant.ogg"},
    {"id":"hw","symbol":"ɥ","group":"glide","name":"圆唇硬腭近音","tip":"从 /y/ 的圆唇、前舌位置迅速滑向后面的元音；和 /w/ 的后舌位置不同。","spelling":"u + 元音（如 huit）","example":"huit","file":"LL-Q150 (fra)-WikiLucas00-IPA ɥ.wav"},
    {"id":"w","symbol":"w","group":"glide","name":"唇软腭近音","tip":"从 /u/ 的圆唇、后舌位置快速滑向后面的元音；如 oui 不要拆成两个音节。","spelling":"ou + 元音、oi 中的 /w/","example":"oui","file":"Voiced labio-velar approximant.ogg"}
  ],
  "examples": {
    "ami":{"id":"ami","ipa":"ami","zh":"朋友"}, "beau":{"id":"beau","ipa":"bo","zh":"美丽的"},
    "dos":{"id":"dos","ipa":"do","zh":"背部"}, "le":{"id":"le","ipa":"lə","zh":"定冠词（阳性单数）"},
    "fou":{"id":"fou","ipa":"fu","zh":"疯狂的"}, "gare":{"id":"gare","ipa":"ɡaʁ","zh":"车站"},
    "chat":{"id":"chat","ipa":"ʃa","zh":"猫"}, "si":{"id":"si","ipa":"si","zh":"如果"},
    "jour":{"id":"jour","ipa":"ʒuʁ","zh":"天；白天"}, "car":{"id":"car","ipa":"kaʁ","zh":"因为"},
    "lit":{"id":"lit","ipa":"li","zh":"床"}, "mot":{"id":"mot","ipa":"mo","zh":"单词"},
    "nous":{"id":"nous","ipa":"nu","zh":"我们"}, "eau":{"id":"eau","ipa":"o","zh":"水"},
    "pas":{"id":"pas","ipa":"pa","zh":"不；步"}, "tu":{"id":"tu","ipa":"ty","zh":"你"},
    "rue":{"id":"rue","ipa":"ʁy","zh":"街道"}, "sac":{"id":"sac","ipa":"sak","zh":"包"},
    "tout":{"id":"tout","ipa":"tu","zh":"全部"}, "vous":{"id":"vous","ipa":"vu","zh":"您；你们"},
    "oui":{"id":"oui","ipa":"wi","zh":"是；对"}, "six":{"id":"six","ipa":"sis","zh":"六（单独读）"},
    "yeux":{"id":"yeux","ipa":"jø","zh":"眼睛（复数）"}, "zéro":{"id":"zero","ipa":"zeʁo","zh":"零"},
    "été":{"id":"ete","ipa":"ete","zh":"夏天"}, "peu":{"id":"peu","ipa":"pø","zh":"少"},
    "mère":{"id":"mere","ipa":"mɛʁ","zh":"母亲"}, "fleur":{"id":"fleur","ipa":"flœʁ","zh":"花"},
    "porte":{"id":"porte","ipa":"pɔʁt","zh":"门"}, "pâte":{"id":"pate","ipa":"pɑt ~ pat","zh":"面团（/ɑ/ 与 /a/ 有口音差异）"},
    "pain":{"id":"pain","ipa":"pɛ̃","zh":"面包"}, "un":{"id":"un","ipa":"œ̃ ~ ɛ̃","zh":"一（鼻元音有口音差异）"},
    "sans":{"id":"sans","ipa":"sɑ̃","zh":"没有"}, "bon":{"id":"bon","ipa":"bɔ̃","zh":"好的"},
    "montagne":{"id":"montagne","ipa":"mɔ̃taɲ","zh":"山"}, "parking":{"id":"parking","ipa":"paʁkiŋ","zh":"停车场"},
    "huit":{"id":"huit","ipa":"ɥit","zh":"八"}, "qui":{"id":"qui","ipa":"ki","zh":"谁"},
    "wagon":{"id":"wagon","ipa":"vaɡɔ̃","zh":"车厢（法国法语常用读音）"}
  }
};
